language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update
  - composer require --dev codeclimate/php-test-reporter:dev-master

install:
  - composer install --prefer-source --no-interaction --dev

before_script:
  - mkdir -p build/logs

script:
  - phpunit --configuration phpunit.xml.dist

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/test-reporter; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'
